In [1]:
# Built in Mathematical Functions in NumPy
import numpy as np  

In [2]:
arr = np.array([3,5,1,3,1,2,4,5,6,7,8,9,10])
# Finding the maximum value in the array
max_value = np.max(arr)
# Finding the minimum value in the array
min_value = np.min(arr)
# Finding the sum of all elements in the array
sum_value = np.sum(arr)

In [3]:
print(max_value)  # Output: 10
print(min_value)  # Output: 1
print(sum_value)  # Output: 56

10
1
64


In [4]:
# Calculate the mean (average) of all elements in the array
mean = arr.mean()

# Calculate the product of all elements in the array
prd = arr.prod()

# Calculate the standard deviation (measure of spread or dispersion)
std_dev = arr.std()

# Calculate the median (middle value) of the array
median = np.median(arr)
# Calculate the variance (measure of how far a set of numbers are spread out)
variance = np.var(arr)

argmax = np.argmax(arr)  # Index of the maximum value
argmin = np.argmin(arr)  # Index of the minimum value

In [ ]:
print(mean)
print(prd)
print(std_dev)
print(median)
print(variance)
print(argmax)  
print(argmin)  

4.923076923076923
54432000
2.8409515865568293
5.0
8.071005917159765
12
2


In [6]:
unique_values = np.unique(arr)  # Unique values in the array
print(unique_values)  

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Compute the natural logarithm of an array.

log = np.log(arr)
print(log)  # Output: natural logarithm of each element in the array

[1.09861229 1.60943791 0.         1.09861229 0.         0.69314718
 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154 2.19722458
 2.30258509]


In [8]:
exp = np.exp(arr)  # Compute the exponential of each element in the array
print(exp)  # Output: e raised to the power of each element in the array

[2.00855369e+01 1.48413159e+02 2.71828183e+00 2.00855369e+01
 2.71828183e+00 7.38905610e+00 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
 2.20264658e+04]


In [9]:
np.percentile(arr,50)

np.float64(5.0)

In [10]:
np.corrcoef(arr, arr)  # Correlation coefficient of the array with itself

array([[1., 1.],
       [1., 1.]])

In [11]:
np.cumsum(arr)  # Cumulative sum of the array

array([ 3,  8,  9, 12, 13, 15, 19, 24, 30, 37, 45, 54, 64])