In [2]:
# indexing in numpy arrays
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
# slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.


In [4]:
b = arr[1:4]

In [5]:
b

array([20, 30, 40])

In [6]:
b[0] = 99  # change the first element of the slice

In [7]:
b

array([99, 30, 40])

In [8]:
arr2  = np.array([10, 99, 30, 40, 50]) 
idx =[0 , 2 ,3]
# advanced indexing
arr2[idx]  # [10 30 40] (select elements at indices

array([10, 30, 40])

In [9]:
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
arr3.flatten()
mask = arr3>30
print(arr3[mask])  # [40 50 60] (select elements greater than 30)

[40 50 60]


In [ ]:
# Create a 3×3 array filled with random numbers and print its shape.
# Convert an array of floats [1.1, 2.2, 3.3] into integers.
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
# Reshape a 1D array of size 9 into a 3×3 matrix.
# Use boolean masking to filter numbers greater than 50 in an array.

In [11]:
arr4 = np.random.rand(3, 3)
print(arr4)  # (3, 3)
print(arr4.shape)  # (3, 3)

[[0.15962652 0.30979987 0.40812192]
 [0.08499488 0.71841598 0.9741766 ]
 [0.75839791 0.59433359 0.79178527]]
(3, 3)


In [12]:
float_array = np.array([1.1, 2.2, 3.3])
int_array = float_array.astype(int)
print(int_array)  # [1 2 3]

[1 2 3]


In [13]:
arr5 = np.array([1, 2, 3, 4, 5, 6])
even_number = arr5[arr5%2==0]
print(even_number)  # [2 4 6]


[2 4 6]


In [17]:
arr6 = np.arange(9)  # Create a 1D array of size 9
print(arr6)  # [0 1 2 3 4 5 6 7 8]
print("changed_array")
reshaped_array = arr6.reshape(3, 3)  # Reshape into a 3x3 matrix
print(reshaped_array)

[0 1 2 3 4 5 6 7 8]
changed_array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
sample_array = np.array([10, 60, 30, 80, 45, 55])
filtered_array = sample_array[sample_array > 50]
print("Numbers greater than 50:", filtered_array)

Numbers greater than 50: [60 80 55]
