In [1]:
# multidimensional indexing in numpy

import numpy as np

In [2]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [3]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
print(arr[0])

[10 20 30]


In [ ]:
np.sum(arr,axis = 0) # axis 0 is the first dimension (rows)

array([50, 70, 90])

In [ ]:
np.sum(arr, axis =1) # axis 1 is the second dimension (columns)

array([ 60, 150])

In [9]:
arr[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [12]:
# indexing in 3d array
arr3D = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])
print(arr3D)
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [15]:
print(arr3D[0,1,2])

6


In [ ]:
print(arr3D[:, 0,:]) # This will select all elements in the first row of each 2D slice

[[1 2 3]
 [7 8 9]]


In [21]:
arr3D[:, 0,:] = 0
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]
