In [2]:
# indexing in numpy arrays
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
# slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.


In [4]:
b = arr[1:4]

In [5]:
b

array([20, 30, 40])

In [6]:
b[0] = 99  # change the first element of the slice

In [7]:
b

array([99, 30, 40])

In [8]:
arr2  = np.array([10, 99, 30, 40, 50]) 
idx =[0 , 2 ,3]
# advanced indexing
arr2[idx]  # [10 30 40] (select elements at indices

array([10, 30, 40])

In [9]:
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
arr3.flatten()
mask = arr3>30
print(arr3[mask])  # [40 50 60] (select elements greater than 30)

[40 50 60]
