In [1]:
#brodcasting in numpy

import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
result = arr ** 2
print(result)

[  1   4   9  16  25  36  49  64  81 100]


In [5]:
result = arr + 10
print(result)

[11 12 13 14 15 16 17 18 19 20]


In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1,2,3])
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Dimensions must be compatible: The size of the trailing dimensions of the arrays must be either the same or one of them must be 1.
# Stretching arrays: If the shapes are compatible, NumPy stretches the smaller array to match the larger one, element-wise, without copying data.


In [7]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
print("Mean:", mean)
print("Standard Deviation:", std)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

Mean: [20. 30. 40.]
Standard Deviation: [7.07106781 7.07106781 7.07106781]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
